[build]
builder = "NIXPACKS"
buildCommand = "npm install --legacy-peer-deps && npm run build"

[deploy]
startCommand = "npm run start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[nixpacks]
nodeVersion = "20"
